GET http://localhost:5000/todo


###
POST http://localhost:5000/todo
Content-Type: application/json

{
    "id": 3,
    "title": "Dat nq",
    "des": "stress"
}

###

PATCH http://localhost:5000/todo/1
Content-Type: application/json

{
    "title": "hihi"
}

###
PUT http://localhost:5000/todo/1
Content-Type: application/json

{
    "title": "hihihihihi"
}

###
DELETE http://localhost:5000/todo/1